INSERT INTO RESOURCE_METADATA (RESOURCE_ID, RESOURCE_CREATOR, RESOURCE_CREATION_DATE_TIME, LAST_MODIFIER, LAST_MODIFIED_DATE_TIME, RESOURCE_OWNER, IS_ACTIVE) values (1, 1,'3.16.2020 10:00 PM', 1, '3.16.2020 10:00 PM', 1, true);


INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (1,'Steven','Kelsey','steven.kelsey@revature.com','Manager of Technology','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (2,'August','Duet','august.duet@revature.com','Lead Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (3,'Nickolas','Jurczak','nickolas.jurczak@revature.com','Lead Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (4,'Wezley','Singleton','wezley.singleton@revature.com','Senior Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (5,'Mitchell','Goshorn','mitchell.goshorn@revature.com','Senior Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (6,'Jason','Knighten','jason.knighten@revature.com','Senior Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (7,'Trevin','Chester','trevin.chester@revature.com','Senior Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (8,'Alexandra','Milevich','alexandra.milevich@revature.com','Senior Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (9,'Robert','Connell','rovert.connell@revature.com','Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (10,'Marielle','Noalesco','marielle.noalesco@revature.com','Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (11,'Jacob','Davis','jacob.davis@revature.com','Trainer','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (12,'Julie','Seals','julie.seals@revature.com','Staging Manager','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (13,'Jonathan','Gworek','jonathan.gworek@revature.com','Quality Analyst','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (14,'Patricia','Nevins','patricia.nevins@revature.com','HR Manager','HR',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (15,'Desiree','Saroniero','desiree.saroniero@revature.com','HR Specialist','HR',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (16,'Kyle','Taylor','kyle.taylor@revature.com','Director of Employee Engagement','DELIVERY',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (17,'Katie','Barakat','katie.barakat@revature.com','Associate Mentor','RECRUITMENT',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (18,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (19,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID ) values (20,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (21,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (22,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (23,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (24,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (25,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (26,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (27,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (28,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (29,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (30,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (31,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (32,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (33,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (34,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (35,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (36,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (37,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (38,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (39,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (40,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (41,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (42,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (43,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (44,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (45,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (46,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (47,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (48,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (49,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (50,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (51,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (52,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (53,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (54,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (55,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (56,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (57,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (58,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (59,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (60,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (61,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (62,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (63,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (64,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (65,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (66,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (67,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )v
--values (68,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (69,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (70,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (71,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (72,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (73,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (74,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (75,'Blake','Dunn','blake.dunn@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (76,'Evan','Hsi','evan.hsi@revature.com','Associate','TRAINING',1);
--INSERT INTO EMPLOYEE (ID, FIRST_NAME, LAST_NAME, EMAIL, TITLE, DEPARTMENT, RESOURCE_METADATA_RESOURCE_ID )
--values (77,'Tyler','Rubbert','tyler.rubbert@revature.com','Associate','TRAINING',1);



